### PR TITLE
[Aesthetic] All Packs Done

### PR DESCRIPTION
**Pull request by NSPC911**
Packs Added:
- Accurate Scaffolding
	- Combination with Unobtrusive Scaffolding
- Consistent Bamboo Planks
- Allay Elytra
- More Zombies

Fixes:
- Fixed Improper Formatting and Keys in packs.json
- Moved extras/variated_stone to extras/variation

Relevant Issues fixed:
- https://github.com/BedrockTweaks/Files/issues/8
- https://github.com/BedrockTweaks/Files/issues/11
- https://github.com/BedrockTweaks/Files/issues/12
- https://github.com/BedrockTweaks/Files/issues/13

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [ ] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [x] (Optional) Tested in Windows
- [x] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by drav0011** [comment]
- Try to keep the commits following the contribution guideline for the following ones
- Separate the more zombies to it's own pull request, that category will need further work apart from what is done to ensure compatibility, will continue the work from what you have done.
- Good for noticing the key issues
- The variation rename is good, but is not a confirmed change, do not make changes like this in the future before opening an issue and discussing it

**Comment by NSPC911** [comment]
- I'll try, the main reason why I stick to mine is because I get confused on what to name them
- More Zombies don't really need any more compatibility AFAIK, not sure what you have planned
- Thanks
- Undo change?

**Comment by NSPC911** [comment]
> No matter how many you select they will have random textures, not just when you choose all of them

So you want more zombies to variate even when two are selected?

**Comment by NSPC911** [comment]
Closed PR. Reason: Switching to separate branches for Aesthetic packs and More Zombies packs

**Pull request closed without merging**
