### PR TITLE
update(files): coloured_sticky_piston_sides

### PR DESCRIPTION
**Pull request by SquatchHunter**
* removed additional files inside coloured slimes
* created combination packs to prevent collisions
* adjusted pistonArmSticky.png in colour slimes to reflect vanilla
fixes: #319
addresses: #71 

note: the combinations are listed below dirt in the packs.json file to hopefully avoid merge conflicts with #317, feel free to move in a future PR / commit.
secondary note: I have only tested black in game, but since the other packs were copy paste, it should be fine... I hope

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [x] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by PAPISOP** [comment]
uhm, actually lets keep english language same in all the instances, as its called "colorful slimes", lets keep the combination folder names to be "color" not "colour"

**Comment by PAPISOP** [comment]
OMG

**Comment by PAPISOP** [comment]
Fix the spelling of color, revert your last commit and make the combinations name to be "color" instead of "colour" for real this time

**Review by NSPC911 — CHANGES_REQUESTED** [review]
really late review, but need black slime as well, you forgot about it i believe
and also there are random `pack_icon.png` files in the combinations for colored_slime

**Comment by PAPISOP** [comment]
> really late review, but need black slime as well, you forgot about it i believe and also there are random `pack_icon.png` files in the combinations for colored_slime

this pr is useless because we will use priority instead of combinations so I don't think this pr will be accepted

**Comment by drav0011** [comment]
As mentioned due to priority this will not be needed, but some notes

>

**Pull request closed without merging**
