### PR TITLE
fix(files): correct translations keys

### PR DESCRIPTION
**Pull request by SquatchHunter**
resolves: #347 

* corrected Cooked Beef to Steak
* corrected Melon to Melon Slice
* correct Enchanted Apple to Enchanted Golden Apple

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [x] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Review by PAPISOP — CHANGES_REQUESTED** [review]
Do it for hunger preview and music disc redstone level preview combinations too

**Review by PAPISOP — CHANGES_REQUESTED** [review]
Do it for other languages too as in those languages the translations are updated with updated names

**Comment by PAPISOP** [comment]
also update pr title to include pack name so that it looks *nicer* and clearer in the changelogs

**Review by drav0011 — APPROVED** [review]
lgtm

**Comment by drav0011** [comment]
The things in the comments above are worth considering

I accepted the PR because of the following
- With new combinations changes the lang files from the combinations will be removed
- The best would be to consider other languages, but english is the priority
- The PR title name should have the name but will not hold a pr just for the naming

**Pull request merged**
