### PR TITLE
update(files): Update Resource Packs to 1.21.50

### PR DESCRIPTION
**Pull request by PAPISOP**
1. Updated Quieter Parrots to quiet the imitation of creaking
2. Updated No Cave Sounds to mute the cave sounds in `individual_named_sounds` which is going to be used in client biome files in the future, currently this change doesn't do anything but this does in fact future proof stuff so that the pack will not break when the cave sounds are controlled by client_biome files
3. Added mangrove leaves and pale oak leaves to Nicer Fast Leaves
4. Updated all the packs that use `grass_side` and `grass_side_bt` in `terrain_texture.json` to work properly in 1.21.50
5. Added pale oak wood type to Glass Doors and Trapdoors, Hanging Sign Logs, Pixel Consistent Signs, Oarless Boats, Old Planks, Circular Log Tops and Variated Planks
6. Updated clearer water and old water to include pale garden biome and added `minecraft:ambient_sounds` to few client biome files from the vanilla
7. Resource packs now only support 1.21.50 and above

NOTE:
1. ~~I wasn't able to add new leaves and wood type to alpha foliage due to not knowing the color code of alpha foliage, so if you know the exact color code then let me know to add them (the pack is not updated in vanilla tweaks)~~ Works as intended by vanilla tweaks (yes)
2. ~~The texture of nether bricks, chiseled nether bricks and cracked nether bricks haven't been updated to the newer ones introduced in 1.21.50 in Black Nether Bricks and Brighter Nether packs. I have held @NSPC911 at a gun point to make the textures for them because vanilla tweaks hasn't updated them~~ @NSPC911 did it in #428 and he is released finally and can see the bright sun on his way back home 

By checking the following boxes with an X, you ensure that:

- [X] The pack was tested ingame in at least one device.
- [X] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [X] The pack code follows the style guide.
- [X] The commits follow the contribution guidelines.
- [X] The PR follows the contribution guidelines.

- [X] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by NSPC911** [comment]
> 2. The texture of nether bricks, chiseled nether bricks and cracked nether bricks haven't been updated to the newer ones introduced in 1.21.50 in Black Nether Bricks and Brighter Nether packs. I have held @NSPC911 at a gun point to make the textures for them because vanilla tweaks hasn't updated them

https://github.com/NSPC911/BT-Files/tree/fix/nether_bricks

**Comment by PAPISOP** [comment]
> > 2. The texture of nether bricks, chiseled nether bricks and cracked nether bricks haven't been updated to the newer ones introduced in 1.21.50 in Black Nether Bricks and Brighter Nether packs. I have held @NSPC911 at a gun point to make the textures for them because vanilla tweaks hasn't updated them
> 
> https://github.com/NSPC911/BT-Files/tree/fix/nether_bricks

Are you finished with it because it doesn't seem like it

**Comment by NSPC911** [comment]
i did not finish it
i did say in the commit that it was proof that i was working on it

**Comment by NSPC911** [comment]
i can finally see my family

**Review by drav0011 — APPROVED** [review]
lgtm

**Pull request merged**
