### PR TITLE
fix(files): Fix all colored hotbar selectors being slightly offset

### LINKED ISSUE #397: [GUI/Hotbar Selector] All Packs
**Pack or combination of packs which has the bug** All Packs in GUI/Hotbar Selector

**Describe the bug**
Colored hotbar selector is slightly offset

**Screenshots**
IMG_5967

**Device (please complete the following information):**
 - OS: All
 - Minecraft Version: 1.21.44

### PR DESCRIPTION
**Pull request by PAPISOP**
1. Made the colored hotbar selectors to be 24x24 from 24x23 to be same as vanilla hotbar selector 
2. No Spyglass Overlay now affects WHAT pack
3. Moved Aesthetic/More Zombies to be below Aesthetic and fixed a missing spacing in the name in `packs.json`
4. Update circular sun and moon's description and name, and update suspicious sand and gravel's name

Resolves #397 

By checking the following boxes with an X, you ensure that:

- [X] The pack was tested ingame in at least one device.
- [X] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [X] The pack code follows the style guide.
- [X] The commits follow the contribution guidelines.
- [X] The PR follows the contribution guidelines.

- [X] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by Chi-a11y** [comment]
tbh I never even saw that pixel off, lgtm

**Comment by SquatchHunter** [comment]
> No Spyglass Overlay now affects WHAT pack

how? iirc these are _meant_ to be Mutually Exclusive packs

**Comment by PAPISOP** [comment]
> > No Spyglass Overlay now affects WHAT pack
> 
> how? iirc these are _meant_ to be Mutually Exclusive packs

Previously I made it so if you select the No Spyglass Overlay and WHAT packs, then WHAT will ignore the No Spyglass Overlay pack and will have the WHAT spyglass overlay with sus sound

Now I made it so that No Spyglass Overlay will actually remove the WHAT spyglass overlay and only the sus sound will remain

**Review by drav0011 — APPROVED** [review]
lgtm

**Pull request merged**
