### PR TITLE
feat(files): Add Classic Minecraft Logo pack

### LINKED ISSUE #54: [Retro] Classic Minecraft Logo
Add pack from Vanilla Tweaks

### PR DESCRIPTION
**Pull request by PAPISOP**
Add Classic Minecraft Logo pack to retro

Resolves #54 

By checking the following boxes with an X, you ensure that:

- [X] The pack was tested ingame in at least one device.
- [X] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [X] The pack code follows the style guide.
- [X] The commits follow the contribution guidelines.
- [X] The PR follows the contribution guidelines.

- [X] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Review by SquatchHunter — APPROVED** [review]
lgtm

**Review by NSPC911 — APPROVED** [review]
lgtm, simple pack honestly

**Comment by PAPISOP** [comment]
> lgtm, simple pack honestly

yeah it just took me 10 minutes to make it lol

**Review by drav0011 — APPROVED** [review]
lgtm
- [x] Tested in Windows

**Pull request merged**
