### PR TITLE
fix(files): Fixed wrong bad omen effect icon showing in dark ui

### LINKED ISSUE #123: [GUI] Dark UI
**Pack or combination of packs which has the bug**
Dark UI

**Describe the bug**
Bad omen effect icon is still using raid omen effect icon (the old bad omen effect icon before 1.21)

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.1

**Additional context**
There is a texture of bad omen effect which needs to be updated to 1.21 new bad omen effect texture

### PR DESCRIPTION
**Pull request by PAPISOP**
Removed textures/gui (I don't think anyone uses old touch GUI anymore)
Removed all the effect icon textures

Resolves #123 

By checking the following boxes with an X, you ensure that:

- [X] The pack was tested ingame in at least one device.
- [X] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [X] The pack code follows the style guide.
- [X] The commits follow the contribution guidelines.
- [X] The PR follows the contribution guidelines.

- [X] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by SquatchHunter** [comment]
is it really as simple as removing all the files?

**Comment by PAPISOP** [comment]
> is it really as simple as removing all the files?
> 
> lgtm if thats the case xD

yeah, but if the gui file still exists, then i need to keep the effect icons (or else all the effect icons will show the gui file image) but DrAv told to remove it as well so there is no need to keep those effect icon textures in the files

**Review by SquatchHunter — APPROVED** [review]
lgtm 👍

**Review by drav0011 — APPROVED** [review]
lgtm
- [x] Tested in Windows

**Comment by drav0011** [comment]
Note: This changes which affect mobile ui should be tested in at least 1 mobile device

**Pull request merged**
