### PR TITLE
fix(files): music_disc_redstone_level

### PR DESCRIPTION
**Pull request by SquatchHunter**
fixes: #228 

* for real this time, fixed all translations should be correct as per the original github, do open an issue if any are wrong

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [x] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by PAPISOP** [comment]
The pack name is different from vanilla tweaks, so is it intentional? Also the pack icon is also different which I think is intentional but if its not then you can update it in this pr @SquatchHunter

**Comment by SquatchHunter** [comment]
name change must of been recent, I have the pack downloaded from VT and it matches exactly
pack icon is just a different disc + the redstone dust texture **I made** and use in game so it matches.

**Comment by PAPISOP** [comment]
> name change must of been recent, I have the pack downloaded from VT and it matches exactly pack icon is just a different disc + the redstone dust texture **I made** and use in game so it matches.

the pack was updated in vanilla tweaks to have a white outline around the redstone dust, so your pack is like i think before that update so probably update it with new pack icon

**Review by drav0011 — APPROVED** [review]
lgtm

**Pull request merged**
