### PR TITLE
fixes(files) general fixes

### PR DESCRIPTION
**Pull request by SquatchHunter**
* capatilised H in beeralis pack [fixes: #170]
* move 3d packs to 3d category [resolves: #132]
* set cave sounds to 0 [fixes: #186]
* remove unused en localisation [fixes: #193]
* fix sounds.json missing key definitions [fixes: #201]
* adjusts "quieter rain" to use sound_definitions.json [refixes: #114]
* fixed old doors not working [fixes: #209]
* fixes "quieter nether portals" by switching to sound_definitions.json method [refixes: #221]

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [x] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by PAPISOP** [comment]
I will recommend to test the peace and quiet packs with/without "sound" key and if its working same as without the "sound" key then remove it

**Comment by SquatchHunter** [comment]
It works without, but you might of missed my question in the discord: Blockception's addon says the pack _should_ be invalid without the sound key present meaning _for future stability reasons_ should we include it or not? is it an oversight on Mojang/Microsoft or is Blockceptions wrong, I wasnt able to find clear documentation for either case so I wanted clarification.

I know DrAv said in past to not include it as the Minecraft backend will fill it in when it does its merging magic, I just want the above clarified.

**Comment by PAPISOP** [comment]
> It works without, but you might of missed my question in the discord: Blockception's addon says the pack _should_ be invalid without the sound key present meaning _for future stability reasons_ should we include it or not? is it an oversight on Mojang/Microsoft or is Blockceptions wrong, I wasnt able to find clear documentation for either case so I wanted clarification.
> 
> I know DrAv said in past to not include it as the Minecraft backend will fill it in when it does its merging magic, I just want the above clarified.

No, it's not required as minecraft backend will add those sound keys by default and in any future update, this will not change because that's how json files filling magic works by minecraft which indeed allows for more future version compatibility and we should only add things to our json files which we have changed and other things should be removed

**Comment by PAPISOP** [comment]
> > packs.json isn't formatted and some other files too @SquatchHunter
> 
> looks good on my end? in browser and IDE, tab size 4 and all tabs not spaces - got a specific example? bare in mind, Github's tab size 4 is different to most IDEs, phones and ect tab size 4 so... you need to actually select the line and check not just compare the visable white space

tab size isnt the problem here, some code doesn't have space between them for eg
```
"id":"3d",
"name":"3D",
"packs":[
```
this is from packs.json and u can see that there isnt a space between `:` and `"3d"` and it should be formatted like this
```
"id": "3d",
"name": "3D",
"packs": [
```
cuz thats how the every ide formats the json code and there are more files which aren't formatted

**Comment by SquatchHunter** [comment]
that really doesnt matter since it all gets compressed anyway
JSON reads the same regardless how many spaces are there, I deliberately stripped all the spaces out and DrAv to my knowledge runs it all through a trim function which will remove new lines + the extra spaces anyway.

**Comment by drav0011** [comment]
The merged files get compressed and minimized, but that is the final product which player will usually not see
Here it is better to keep consistency between the whole project for ease to read and consistency. Most IDE's default JSON formatting with a space after the colon, but not before so we should keep it that way.

Otherwise changed look good, except for Nether Portal Sounds. Seems like teleporting in and out of the nether still plays the sound loud

**Comment by SquatchHunter** [comment]
> The merged files get compressed and minimized, but that is the final product which player will usually not see Here it is better to keep consistency between the whole project for ease to read and consistency. Most IDE's default JSON formatting with a space after the colon, but not before so we should keep it that way.

> Otherwise changed look good, except for Nether Portal Sounds. Seems like teleporting in and out of the nether still plays the sound loud

wasnt aware that Nether Portal sounds is playing up, ill check and commit a fix to that and reformat the spacing

**Comment by PAPISOP** [comment]
To avoid merge conflicts can you update the pack icon for 3d sun & moon from vanilla tweaks @SquatchHunter

**Review by drav0011 — APPROVED** [review]
lgtm

**Pull request merged**
