### PR TITLE
fix(files): Fix bad omen showing wrong icon in dark numbered hotbar

### LINKED ISSUE #123: [GUI] Dark UI
**Pack or combination of packs which has the bug**
Dark UI

**Describe the bug**
Bad omen effect icon is still using raid omen effect icon (the old bad omen effect icon before 1.21)

**Device (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.1

**Additional context**
There is a texture of bad omen effect which needs to be updated to 1.21 new bad omen effect texture

### PR DESCRIPTION
**Pull request by PAPISOP**
This is the same issue as #123 and same changes have been made as #127, but I didn't see this combination so this pr should also fix this issue in dark numbered hotbar combination

Resolves #123 

By checking the following boxes with an X, you ensure that:

- [X] The pack was tested ingame in at least one device.
- [X] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [X] The pack code follows the style guide.
- [X] The commits follow the contribution guidelines.
- [X] The PR follows the contribution guidelines.

- [X] (Optional) Tested in Windows
- [X] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by NSPC911** [comment]
Honestly not sure why you are removing the icons in textures/ui because just removing textures/ui/gui.png is good enough. It just isn't able to properly map the icon and just uses the whole texture, hence the issues

**Comment by PAPISOP** [comment]
> Honestly not sure why you are removing the icons in textures/ui because just removing textures/ui/gui.png is good enough. It just isn't able to properly map the icon and just uses the whole texture, hence the issues

I am removing the effect icon textures because that's what DrAv said in the issue, and now it will use the files from vanilla so there is no tension of updating effect icons in dark ui. Also if you have gui file then the effect icon textures should not be removed as it will the entire gui file image as effect icon for each effect (idk why it does that but it does do it) but DrAv also said that remove gui file because no body uses old touch gui so there is no need to keep those files (I have already explained this in my original pr for this issue which is #127 but again i explained it again with more information)

**Review by SquatchHunter — APPROVED** [review]
lgtm

however, since the old PR was successfully merged, you probably dont need to make the same edits but rather just sync your fork to the main repo, but I do not think it really matters.

**Comment by PAPISOP** [comment]
> lgtm
> 
> however, since the old PR was successfully merged, you probably dont need to make the same edits but rather just sync your fork to the main repo, but I do not think it really matters.

I did do a new commit to the same branch which got merged but it wasn't reflected in the devel branch so i created a new pr

**Comment by SquatchHunter** [comment]
yea, if the commit came post merge, you will need a new PR to make the changes

**Comment by drav0011** [comment]
Before sending a new pr, pull changes from devel, merge them into your branch and then push the branch

**Review by drav0011 — APPROVED** [review]
lgtm

**Comment by SquatchHunter** [comment]
> Before sending a new pr, pull changes from devel, merge them into your branch and then push the branch

ill be honest, I did that but was having issues pulling it down to my local copy so thats why there is 2 "sync" commits on this branch, for x reason my local git repo was refusing to sync with my github repo that had exactly the same files on it but was throwing errors.

**Pull request merged**
