### PR TITLE
fix(files): java_maps

### PR DESCRIPTION
**Pull request by SquatchHunter**
fixes: #257 

* adds missing map_trial_chambers.png

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [x] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by drav0011** [comment]
Trial maps texture is pink/orange ish instead of black, could you update that?
image

**Comment by SquatchHunter** [comment]
where?
the wiki shows it as black

**Comment by drav0011** [comment]
I just went ingame without any resource packs an checked the color

**Comment by SquatchHunter** [comment]
weird that git commit --amend requires a force push to update gh but oh well

@drav0011 this pr is ready for review

**Review by drav0011 — APPROVED** [review]
lgtm

**Pull request merged**
