### PR TITLE
feat(files): QOL Copper Powered Rails

### LINKED ISSUE #135: [Quality of Life] Copper Powered Rails
Add pack from vanilla tweaks

### PR DESCRIPTION
**Pull request by Chi-a11y**
Resolves #135 
- Added Copper Powered Rails

By checking the following boxes with an X, you ensure that:

- [X] The pack was tested ingame in at least one device.
- [X] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [X] The pack code follows the style guide.
- [X] The commits follow the contribution guidelines.
- [X] The PR follows the contribution guidelines.

- [X] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Review by SquatchHunter — APPROVED** [review]
Looks good to me, but change the format_version to 1.21.

It wont do anything functionally afaik but lets a future maintainer check which version the pack is

**Comment by PAPISOP** [comment]
Also add priority key to match other crafting tweaks, usually they are set to "-1"

**Comment by drav0011** [comment]
Check formatting for the recipe, it should be tab size 4
Also about naming, follow the same pattern as the other CT's
`crafting_tweaks/files/quality_of_life/copper_powered_rails/recipes/copper_powered_rails/powered_rail.recipe.json`
instead of
`crafting_tweaks/files/quality_of_life/copper_powered_rails/recipes/powered_rail_from_copper/powered_rail_from_copper.recipe.json`

**Review by SquatchHunter — CHANGES_REQUESTED** [review]
as DrAv has pointed out and I am now bumping this issue, format the files to be a tab size 4 (VSC has built in functions for this if you use it) and keep the naming scheme the same as other packs

**Review by SquatchHunter — APPROVED** [review]
lgtm

**Review by drav0011 — APPROVED** [review]
lgtm

**Pull request merged**
