### PR TITLE
fix(files): Made Dark UI usable and added two combinations

### LINKED ISSUE #223: [GUI] Dark UI
Dark UI inconsistency

there are some inconsistency in dark UI some item outline are grey(e.g. loom)
Screenshot_2024-07-30-16-26-32-22

 And other are white(e.g. brewing stand)
Screenshot_2024-07-30-16-26-01-56

 - Android 10
 - Minecraft Version: 1.21.2.02

**Additional context**

### PR DESCRIPTION
**Pull request by PAPISOP**
Made Dark UI usable by fixing 90% of the bugs in it
Added dark_brewing_stand_icons_fix and dark_numbered_hotbar_brewing_stand_icons_fix combinations

Here's the changes which I did and keep in mind that it might not contain all the changes made:

1. removed loading bar texture as it was looking very bad and default texture looks good with it and making it white using json ui
2. intentionally made empty potion bottle icon in brewing stand ui to have two extra pixels on the bottom to be consistent with bedrock ui and if a person wants to fix it then they need to choose both dark ui and brewing stand icons fix 
3. added white outline around 3 ui icons in loom (loom_pattern_item_empty will need to be updated when 1.21.30 releases as this button texture will change cuz of new banner pattern) 
4. added white outline around 3 ui icons animations in smithing table
5. fixed many non darken ui elements in brewing stand pocket ui
6. fixed dropdowns in settings and form uis not being darkened
7. updated toggle_off (hover too) and crafting toggle off (hover too) to use updated textures
8. fixed how to play button not being darkened
9. fixed sliders progress not getting darkened
10. fixed the tab behind close button not being darkened in play screen
11. fixed the 4 emote wheels still using green color hover
12. fixed dropdown chevro being grey
13. fixed dropdown disabled being not darkened
14. fixed disabled buttons being not darkened
15. fixed slider locked button and bg not being darkened
16. fixed close button in pocket ui in some uis such as furnace
17. fixed sacred enchanting texts cant be visible in enchantment table
18. fixed empty saddle, armor and carpet in horse, donkey, mule and llama 
19. fixed left and right icons being grey in skin picker
20. fixed minecoin purchase plus sign being grey
21. fixed back button color being grey 
22. made keyboard down in chat screen to be white
23. fixed minimize button not being white
24. fixed multi selection icon not being darkened in storage
25. made the border around text input such as in chat screen darkened
26. fixed texts being grey in sort and filter menus in marketplace search screen
27. fixed the radio filled being not darkened when creating a new character in dressing room
28. made the refresh icon during a skin loading failure white
29. fixed the border around show more button in a marketplace item listing being white
30. fixed the title text in choosing a character in dressing room with adjustments made to background of each character to be darker
31. fixed some buttons colors to be not grey in my content in marketplace
32. fixed trash button in npc advanced screen
33. fixed back button
34. fixed loading spin by making it white
35. made the trade icon in trade menu in pocket to have white arrows
36. made the expand button in inventory menu in pocket to be white 
37. made locked recipe items to be dark red in recipe book
38. cleaned up files which are exactly same as vanilla for better compatibility and maintenance (consequently fixing compatibility issues with gui/hunger bars packs)

**Keep in mind that it might contain more bugs so lemme know if you find any but as of now this pack can be usable and bugs will be minor**

Resolves #223 

By checking the following boxes with an X, you ensure that:

- [X] The pack was tested ingame in at least one device.
- [X] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [X] The pack code follows the style guide.
- [X] The commits follow the contribution guidelines.
- [X] The PR follows the contribution guidelines.

- [X] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by SquatchHunter** [comment]
946 files is too many.
Chrome quite literally cannot handle it, my pc doesnt even break a sweat but chromes internal process manager is like "woah, chill" and just nukes long running processes

**Comment by PAPISOP** [comment]
> 946 files is too many. Chrome quite literally cannot handle it, my pc doesnt even break a sweat but chromes internal process manager is like "woah, chill" and just nukes long running processes
> 
> from what I have seen, it looks good but its going to take time to confirm.

DrAv doesn't need to look up all the changes, he only needs to see the changes made in dark ui pack as I have just copied pasted the same pack for combinations with brewing stand icon fix and numbered hotbar. If you ignore those then the total file changes will be around 300

**Comment by NSPC911** [comment]
> Chrome quite literally cannot handle it, my pc doesnt even break a sweat but chromes internal process manager is like "woah, chill" and just nukes long running processes

use firefox smh

**Review by NSPC911 — APPROVED** [review]
good ig

**Comment by SquatchHunter** [comment]
> use firefox smh

the issue realistically is with github's code not the browser, since my PC outside of chrome is fine and has plenty of capacity, just chromes limited resources and githubs performance poor system struggle
I was looking at it the other day
for x reason, every time a button is clicked on the "files changes" tab it redraws the entire page from top to bottom
even just hovering a button causes a redraw
and with how intensive it is, it just freaks out

**Comment by drav0011** [comment]
Looks great!

>Keep in mind that it might contain more bugs so lemme know if you find any but as of now this pack can be usable and bugs will be minor

A couple of issues, feedback button panel does not seem to have dark ui
image

Crafting toggle still has green overlay
image
image

And 2nd, 3rd and 4th tabs in crafting menu seem to not work in selected and selected:hover states
image
image

**Review by drav0011 — APPROVED** [review]
lgtm

**Pull request merged**
