### PR TITLE
feat(files): Add Emerald to Rubies + Pre 1.17 Ores + Ore Borders Combinations

### PR DESCRIPTION
**Pull request by MPAD2277**
<description_pr>

By checking the following boxes with an X, you ensure that:

- [X] The pack was tested ingame in at least one device.
- [X] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [X] The pack code follows the style guide.
- [ ] The commits follow the contribution guidelines.
- [X] The PR follows the contribution guidelines.

- [ ] (Optional) Tested in Windows
- [X] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by SquatchHunter** [comment]
I see you didnt tick the "commits follow style guide"
it should be easy enough to fix with a rebase, but since all the work is done, you can either rebase in one commit or let someone else do it with credit of course.

otherwise lgtm

**Comment by NSPC911** [comment]
rebase just adds previous commits to your local repo iirc
squash merges all commits into one

**Comment by MPAD2277** [comment]
> I see you didnt tick the "commits follow style guide" it should be easy enough to fix with a rebase, but since all the work is done, you can either rebase in one commit or let someone else do it with credit of course.
> 
> otherwise lgtm

How do i commit all of them at once? I'm in mobile, i dont have any pc/laptop.

**Comment by MPAD2277** [comment]
Should i remake? The commit and pr isn't according to guidelines. I even didn't use new branch.

**Comment by SquatchHunter** [comment]
if the changes are good, me or NSPG or DrAv can always just quickly squash & rebase and upload pull on your behalf with credit.
otherwise you can do the same;
rough steps would be to squash your commits with a new message, rebase to a new branch with the correct name and make a new PR and close this one.

**Comment by MPAD2277** [comment]
Ok imma close this pr

**Pull request closed without merging**
