### PR TITLE
feat(files): More Zombies

### PR DESCRIPTION
**Pull request by NSPC911**
No combinations though, just a base for DrAV

Packs Added:
- Steve Zombies
- Alex Zombies
- Ari Zombies
- Efe Zombies
- Kai Zombies
- Makena Zombies
- Noor Zombies
- Sunny Zombies
- Zuri Zombies

Partially Resolves: #13 

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [x] (Optional) Tested in Windows
- [x] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by PAPISOP** [comment]
In vanilla tweaks, if you choose all the packs in more zombies, then it will randomize the texture for each zombie entity, so I think you should also add this feature to your work, because DrAv might ask you to add this feature because there is already an issue for adding the more zombies randomised variants description under the category in #14

**Comment by SquatchHunter** [comment]
this was addressed in the discord as not being finished, it merely here for someone to take and finish afaik

**Comment by drav0011** [comment]
Updated to allow randomized variants between any selected zombie skins

**Review by NSPC911 — COMMENTED** [review]
seems good
is it pushing from your branch or my branch?

**Comment by drav0011** [comment]
@NSPC911 It is you branch and I pushed changes to it

**Pull request merged**
