### PR TITLE
feat(files): fully_aged_amethyst_cluster_marker

### PR DESCRIPTION
**Pull request by drav0011**
added pack
note: left bt_glint.png in case there is needed to make changes to have the base texture

Glint by @Chi-a11y

Resolves https://github.com/BedrockTweaks/Files/issues/35

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [x] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by drav0011** [comment]
Ignore missclicks

**Comment by PAPISOP** [comment]
I think the pr name should not be this lol @drav0011

**Comment by drav0011** [comment]
🤦

**Review by NSPC911 — CHANGES_REQUESTED** [review]
You don't really have to spam the same texture frames
https://wiki.bedrock.dev/blocks/flipbook-textures.html#flipbook-texture-parameters
Use frames to define how you want the flipbook to go through and blend frames to make it smoother

**Comment by drav0011** [comment]
Updated to use frames

**Review by NSPC911 — CHANGES_REQUESTED** [review]
still need ticks per frame iirc, frames just defines how it uses the flipbook texture

**Comment by drav0011** [comment]
Those seem incompatible between them from what I tested, in this way works ingame

**Pull request merged**
