### PR TITLE
fix(feat): fixes ore borders and rubies

### PR DESCRIPTION
**Pull request by yzabeast1**
fixes other emerald items not changing when emerald to rubies and ore borders are selected

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [ ] (Optional) Tested in Windows
- [x] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by yzabeast1** [comment]
I just copied over the text files from the emerald to rubies pack

**Comment by drav0011** [comment]
Texts were there from previous versions, and it would be better to have them translated or leave only english translations as some players might not understand english and still use the packs.

If you could also change or remove the translations from the normal pack would be great!

**Comment by SquatchHunter** [comment]
bump? yza have you added the changes that were requested?

**Comment by yzabeast1** [comment]
This PR was implemented in papi's combination fix PR and is no longer needed

**Comment by SquatchHunter** [comment]
ah, if so could you mark as closed :)

**Pull request closed without merging**
