### PR TITLE
feat(files): GUI Hotbar Selector

### LINKED ISSUE #322: [GUI] Hotbar Selector
Add all hotbar selector packs

### PR DESCRIPTION
**Pull request by Chi-a11y**
Resolves #322 
Added all 14 Hotbar Selectors

By checking the following boxes with an X, you ensure that:

- [X] The pack was tested ingame in at least one device.
- [X] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [X] The pack code follows the style guide.
- [X] The commits follow the contribution guidelines.
- [X] The PR follows the contribution guidelines.

- [X] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by PAPISOP** [comment]
As the packs are lowered than dark ui, dark ui will take the priority and overwrites them, resulting them to be incompatible with dark ui, seems like DrAv has to make exclusions for this category to have higher priority than dark ui even tho its lower the dark ui

**Comment by drav0011** [comment]
Great

What mentioned @PAPISOP is right, but now there is priority to avoid this

Could you @Chi-a11y update the packs.json to include priority 1 for this packs?
Here is the documentation for it

```
https://github.com/BedrockTweaks/Files/blob/devel/CONTRIBUTING.md#pack-priority
export interface Pack {
  id: string;
  name: string;
  description: string;
  message?: Message;
  version?: string; // * only Addons and CT
  priority?: number; // Higher number, higher priority
}
```

**Comment by QANQUES** [comment]
Bro pls dont send me

😭


20 Eki 2024 Paz 11:29 tarihinde DrAv0011 ***@***.***> şunu
yazdı:

**Review by drav0011 — APPROVED** [review]
lgtm

**Pull request merged**
