### PR TITLE
Feat(files): Emerald to Rubies + Pre 1.17 Ores + Ore Borders Combinations

### PR DESCRIPTION
**Pull request by MPAD2277**
Adds 2 combinations for Emerald to Rubies + Pre 1.17 + Ore Borders (ik its a small change lol}

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [ ] (Optional) Tested in Windows
- [x] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Review by NSPC911 — APPROVED** [review]
lgtm, good that you squashed and merged (unlike me)

**Comment by MPAD2277** [comment]
> lgtm, good that you squashed and merged (unlike me)

Thanks bro

**Review by SquatchHunter — APPROVED** [review]
lgtm 👍

**Comment by drav0011** [comment]
Combinations packs must have all files from all combinations, not just the changes made
Ex:
extras/ores/pre_1_17_rubies_ore_borders
should have all the files from this 3 packs
utility/ore_borders
fun/emeralds_to_rubies
retro/pre_1_17_ores

**Comment by MPAD2277** [comment]
> Combinations packs must have all files from all combinations, not just the changes made Ex: extras/ores/pre_1_17_rubies_ore_borders should have all the files from this 3 packs utility/ore_borders fun/emeralds_to_rubies retro/pre_1_17_ores

So i have to add new texture from ore borders, and pre 1.17 ores?

**Comment by SquatchHunter** [comment]
could be that there is missing combinations there aswell as per #71

**Comment by drav0011** [comment]
> So i have to add new texture from ore borders, and pre 1.17 ores? But if i see in "extras/ores/rubies_ore_borders (or any combinations with rubies)" it just change the emerald texture to rubies but with border.
The "easy" way is to download the combination from vanilla tweaks, and all files that are there convert them into bedrock format

**Comment by drav0011** [comment]
Any updates on this?

**Comment by MPAD2277** [comment]
> Any updates on this?

Sorry bruv, i no update for this, might close this pr then make a new one for more ore combinations

**Pull request closed without merging**
