### PR TITLE
fix(files): back_to_blocks

### PR DESCRIPTION
**Pull request by drav0011**
fixed back to blocks slabs crafting output being 3 blocks instead of 2

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [x] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Comment by SquatchHunter** [comment]
lgtm, I cannot check that every block is done, away from home atm

**Comment by yzabeast1** [comment]
why does putting in 2 slabs give back 2 blocks? it should be 2 slabs to one block as thats how vanilla tweaks has it and otherwise you could dupe blocks by turning them to slabs and back

**Comment by SquatchHunter** [comment]
goood point.

**Review by SquatchHunter — CHANGES_REQUESTED** [review]
as Yza has correctly pointed out - why are slabs not 2:1 ratio since they are a 1:2 ratio when crafting?
~~how was it ever three??~~

**Comment by drav0011** [comment]
> why does putting in 2 slabs give back 2 blocks? it should be 2 slabs to one block as thats how vanilla tweaks has it and otherwise you could dupe blocks by turning them to slabs and back

brain not braining, fixed

**Review by NSPC911 — APPROVED** [review]
lgtm, how did it even become 3 blocks?

**Review by SquatchHunter — APPROVED** [review]
> lgtm, how did it even become 3 blocks?

this is what I wanna know
however PR is lgtm 👍

**Comment by yzabeast1** [comment]
Probably the stair recipe was copied with the input changed but he forgot to change the output

**Pull request merged**
