### PR TITLE
update(files): Update Fixes category to 1.21 and add new packs to it

### LINKED ISSUE #70: [Fixes] Update category
Add new fixes if applicable to bedrock
Check if existing fixes still applicable, if not remove

### PR DESCRIPTION
**Pull request by PAPISOP**
**Added Packs:**
1. Consistent Blank Decorated Pot
2. Brighter Rib Armor Trim
3. Hanging Sign Logs
4. Consistent Smooth Stone
5. Brewing Stand Icons Fix

**Removed Packs:**
1. Removed Pixel Consistent Bat as it is no longer needed because of new bat texture
2. Removed Consistent Oars as it was implemented by minecraft in 1.19 update and also removed by vanilla tweaks

**Added Packs Combination:**
1. Updated Observer Texture and Directional Observers

**Changes in Packs:**
1. Renamed category "Fixes" to "Fixes and Consistency" to match vanilla tweaks
2. Changed Updated Observer Texture to actually changes the texture according to vanilla tweaks and not adding redstone lit on (on state doesn't even work) and off on the texture
3. Updated wither texture from vanilla tweaks in Pixel Consistent Wither
4. Updated textures of all the signs entity in Pixel Consistent Sign from vanilla tweaks
5. Added mangrove sign, cherry sign, and bamboo sign to Pixel Consistent Sign
6. Fixed experience orb looking different from vanilla tweaks one in Pixel Consistent Experience Orbs
7. Updated beacon_beam texture from vanilla tweaks in Pixel Consistent Beacon Beam
8. Updated guardian_beam texture from vanilla tweaks in Pixel Consistent Guardian Beam
9. Added cherry leaves and flowering azalea leaves to Nicer Fast Leaves
10. Added polished tuff slab to Double Slab Fix
11. Fixed polished deepslate slab up and down textures are using double slab line texture instead of their block texture in Double Slab Fix
12. Removed cut copper slab, exposed cut copper slab,  weathered cut copper slab, and oxidized cut copper slab from Double Slab Fix as they are acting same as vanilla behavior (these textures still exist in vanilla tweaks but in bedrock we dont need it)
13. Fixed format_version of blocks.json to use an array instead of string which is wrong
14. Updated iron_hoe, stone_hoe, and wood_hoe textures from vanilla tweaks in Hoe Fix
15. Rearranged packs position to match vanilla tweaks
16. Changed Smoker Bottom Fix description to match vanilla tweaks
17. Updated beacon_beam texture in pixel_consistent_bacon_beam combination

Resolves #70

By checking the following boxes with an X, you ensure that:

- [X] The pack was tested ingame in at least one device.
- [X] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [X] The pack code follows the style guide.
- [X] The commits follow the contribution guidelines.
- [X] The PR follows the contribution guidelines.

- [X] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

### CODE REVIEW

**Review by NSPC911 — APPROVED** [review]
holy crap you cooked lol, you just took an entire category for yourself like me lmao

stuff that I thought of
- The renaming of fixes to fixes_and_consistency was something that I doubt DrAV will approve, but considering that VT has it named like that, eh
- It is true that bedrock doesn't exactly need a copper double slab fix, but it is up to DrAV again
- The rescaling is probably to make it more accurate and _consistent_, but considering that bedrock can't handle 128x+ textures (except on good GPUs), again eh

lgtm as always, but I'm using GitHub CLI, so I can't bother opening the image files

**Comment by PAPISOP** [comment]
> The renaming of fixes to fixes_and_consistency was something that I doubt DrAV will approve, but considering that VT has it named like that, eh
Vanilla Tweaks renamed the category so maybe DrAv might approve because he wants bedrock tweaks to be as similar to Vanilla Tweaks

> It is true that bedrock doesn't exactly need a copper double slab fix, but it is up to DrAV again
Yeah because even if you add the textures, it will not make any difference 

> The rescaling is probably to make it more accurate and consistent, but considering that bedrock can't handle 128x+ textures (except on good GPUs), again eh
Vanilla tweaks also uses 16x16 texture and when I rescaled it to 16x16, I didn't see a difference and it also increases performance

**Comment by PAPISOP** [comment]
Fix format_version and fix a typo commits are sneaky commits to fix very minor issues

**Review by drav0011 — APPROVED** [review]
lgtm

**Comment by drav0011** [comment]
@PAPISOP Could you resolve the conflicts?
Apart from that everything seems good!

- [x] Tested in Win11

**Comment by PAPISOP** [comment]
> @PAPISOP Could you resolve the conflicts? Apart from that everything seems good!
> 
> * [x]  Tested in Win11

I can, but it might result 3k+ files changed so, that's why I haven't did it so that u can review the real changes b4, cant you force merge cuz when i was trying i was getting an error in git so i leave it

**Review by drav0011 — APPROVED** [review]
lgtm

**Pull request merged**
